app/Http/routes.php
<?php

Route::get('/', function () { return redirect('home'); });
Route::get('home', function () { return redirect()->route('leaves.index'); });

Route::controller('auth', 'Auth\AuthController');

Route::get('auth/logout', [
    'uses' => function () {
        Auth::logout();
        return redirect('auth/login');
    },
    'as' => 'auth.logout'
]);

Route::group(['middleware' => 'auth'], function () {

    Route::resource('users', 'UsersController');

    Route::resource('leave-types', 'LeaveTypesController');

    Route::put('leaves/{id}/approve', [
        'uses' => 'LeavesController@approve',
        'as'   => 'leaves.approve'
    ]);
    Route::put('leaves/{id}/reject', [
        'uses' => 'LeavesController@reject',
        'as'   => 'leaves.reject'
    ]);
    Route::resource('leaves', 'LeavesController');

});

app/Models/Leave.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Leave extends Model
{
    protected $fillable = [
        'duration',
        'from',
        'to',
        'reason',
        'status',
        'leave_type_id',
        'user_id',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function leaveType()
    {
        return $this->belongsTo(LeaveType::class);
    }
}

app/Models/LeaveType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class LeaveType extends Model
{
    public $timestamps = false;

    protected $fillable = [
        'name'
    ];
}

app/Http/Controllers/LeavesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Leave;
use App\Models\LeaveType;
use App\Models\Support\LeaveDuration;
use App\Models\Support\LeaveStatus;
use App\Models\User;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;

class LeavesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $user = Auth::user();

        if ($user->is_admin) {
            $view = 'leaves.index_admin';
            $leaves = Leave::all();
        }
        else {
            $view = 'leaves.index_staff';
            $leaves = $user->leaves;
        }

        return view($view, compact('leaves'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $types = LeaveType::all()->lists('name', 'id');

        return view('leaves.create', compact('types'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        $data = $request->only([
            'leave_type_id',
            'duration',
            'from',
            'to',
            'reason'
        ]);

        $availableDurations = LeaveDuration::getDurations();
        $this->validate($request, [
            'leave_type_id' => 'required|exists:leave_types,id',
            'duration'      => 'required|in:' . implode(',', array_keys($availableDurations)),
            'from'          => 'required|date_format:Y-m-d',
            'to'            => 'required|date_format:Y-m-d|min:from',
            'reason'        => 'required'
        ]);

        $data['status'] = LeaveStatus::PENDING; // Set default status by "pending" when create
        $result = $this->getCurrentUser()->leaves()->create($data);

        return redirect()->route('leaves.index');
    }

    public function show($id)
    {
        try {
            $leave = Leave::findOrFail($id);
        } catch (ModelNotFoundException $ex) {
            return app()->abort(404);
        }

        return [
            'data' => $leave
        ];
    }

    public function approve($id)
    {
        try {
            $leave = Leave::findOrFail($id);
        } catch (ModelNotFoundException $ex) {
            return app()->abort(404);
        }

        // Only admin can approve
        if ( ! $this->isCurrentUserAdmin()) {
            return app()->abort(403);
        }

        // Only approvable if currently is pending
        if ($leave->status != LeaveStatus::PENDING) {
            return [
                'message' => 'This leave is not approvable'
            ];
        }

        $leave->status = LeaveStatus::APPROVED;
        $result = $leave->save();

        return [
            'success' => $result
        ];
    }

    public function reject($id)
    {
        try {
            $leave = Leave::findOrFail($id);
        } catch (ModelNotFoundException $ex) {
            return app()->abort(404);
        }

        // Only admin can reject
        if ( ! $this->isCurrentUserAdmin()) {
            return app()->abort(403);
        }

        // Only rejectable if currently is pending
        if ($leave->status != LeaveStatus::PENDING) {
            return [
                'message' => 'This leave is not rejectable'
            ];
        }

        $leave->status = LeaveStatus::REJECTED;
        $result = $leave->save();

        return [
            'success' => $result
        ];
    }

    /**
     * @return User
     */
    protected function getCurrentUser()
    {
        return Auth::user();
    }

    protected function isCurrentUserAdmin()
    {
        return $this->getCurrentUser()->is_admin;
    }
}

resources/views/leaves/create.blade.php
@extends('layout')

@section('content')
    <form action="{{ route('leaves.store') }}" method="post">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">

        <div class="form-group">
            <label>Type</label>
            @include('components.error_message', ['field' => 'leave_type_id'])
            {!! Form::select('leave_type_id', $types, old('leave_type_id'), ['class' => 'form-control']) !!}
        </div>
        <div class="form-group">
            <label>Duration</label>
            @include('components.error_message', ['field' => 'duration'])
            {!! Form::select('duration', LeaveDuration::getDurations(), old('duration'), ['class' => 'form-control']) !!}
        </div>
        <div class="form-group">
            <label>Leaving range</label>
            @include('components.error_message', ['field' => 'from'])
            @include('components.error_message', ['field' => 'to'])
            <div class="input-daterange input-group" id="datepicker">
                <input type="text" class="input-sm form-control" name="from" value="{{ old('from') }}">
                <span class="input-group-addon">to</span>
                <input type="text" class="input-sm form-control" name="to" value="{{ old('to') }}">
            </div>
        </div>
        <div class="form-group">
            <label>Reason</label>
            @include('components.error_message', ['field' => 'reason'])
            <textarea name="reason" rows="10" class="form-control">{{ old('reason') }}</textarea>
        </div>
        <div class="form-group text-center">
            <button class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-floppy-disk"></i> Save</button>
        </div>
    </form>
@append

@section('css')
    <link rel="stylesheet" href="{{ asset('bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}">
@append

@section('js')
    <script src="{{ asset('bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
    <script>
        $(function () {
            $(".input-daterange").datepicker({
                format: "dd-mm-yyyy",
                startDate: new Date()
            });
        })
    </script>
@append

resources/views/leaves/index_admin.blade.php
@extends('layout')

@section('content')
    <a href="{{ route('leaves.create') }}" class="btn btn-default btn-sm">
        <i class="glyphicon glyphicon-plus-sign"></i> Create new leave
    </a>
    <table class="table table-striped">
        <thead>
            <th>User</th>
            <th>Type</th>
            <th>From</th>
            <th>To</th>
            <th>Reason</th>
            <th class="text-center">Action</th>
        </thead>
        <tbody>
            @forelse($leaves as $leave)
                <tr>
                    <td>{{ $leave->user->name }}</td>
                    <td>{{ $leave->leaveType->name }}</td>
                    <td>{{ $leave->from }}</td>
                    <td>{{ $leave->to }}</td>
                    <td>
                        <a href="#" class="btn-view-leave-reason btn btn-info btn-xs"
                           data-url="{{ route('leaves.show', $leave->id) }}">
                            <i class="glyphicon glyphicon-book"></i> View reason
                        </a>
                    </td>
                    <td class="text-center">
                        @if($leave->status == LeaveStatus::PENDING)
                            <div class="btn-group btn-group-xs">
                                <a href="#" class="btn btn-success btn-approve-leave"
                                   data-url="{{ route('leaves.approve', $leave->id) }}">
                                    <i class="glyphicon glyphicon-thumbs-up"></i>
                                </a>
                                <a href="#" class="btn btn-danger btn-reject-leave"
                                   data-url="{{ route('leaves.reject', $leave->id) }}">
                                    <i class="glyphicon glyphicon-thumbs-down"></i>
                                </a>
                            </div>
                        @elseif($leave->status == LeaveStatus::APPROVED)
                            <span class="label label-success">Approved</span>
                        @else
                            <span class="label" style="background-color: black;">Rejected</span>
                        @endif
                    </td>
                </tr>
            @empty
                <tr class="bg-info text-center">
                    <td colspan="6">There's currently no leaves</td>
                </tr>
            @endforelse
        </tbody>
    </table>
@append

@section('js')
    <script>
        $(function () {
            $(".btn-view-leave-reason").click(function () {
                var url = $(this).data("url");

                $.get(url).success(function (result) {
                    var reason = result.data.reason;
                    alert(reason);
                });
            });

            $(".btn-approve-leave").click(function () {
                var btn = $(this);
                var url = btn.data("url");
                var token = $("html").data("token");

                // Confirm before approve
                if( ! confirm("Approve this leave?")) return;

                $.ajax({
                    url: url,
                    method: "put",
                    data: {
                        _token: token
                    }
                }).success(function (result) {
                    if (result.success) {
                        var td = btn.closest("td");
                        td.html("").append($("<span class='label label-success'>").text("Approved"));
                    }
                    else {
                        var message = result.message ? result.message : "Failed to approve the leave";
                        alert(message);
                    }
                });
            });

            $(".btn-reject-leave").click(function () {
                var btn = $(this);
                var url = btn.data("url");
                var token = $("html").data("token");

                // Confirm before approve
                if( ! confirm("Reject this leave?")) return;

                $.ajax({
                    url: url,
                    method: "put",
                    data: {
                        _token: token
                    }
                }).success(function (result) {
                    if (result.success) {
                        var td = btn.closest("td");
                        td.html("").append($("<span class='label' style='background-color: black;'>").text("Rejected"));
                    }
                    else {
                        var message = result.message ? result.message : "Failed to reject the leave";
                        alert(message);
                    }
                });
            });
        })
    </script>
@append

resources/views/leaves/index_staff.blade.php
@extends('layout')

@section('content')
    <a href="{{ route('leaves.create') }}" class="btn btn-default btn-sm">
        <i class="glyphicon glyphicon-plus-sign"></i> Create new leave
    </a>
    <table class="table table-striped">
        <thead>
            <th>User</th>
            <th>Type</th>
            <th>From</th>
            <th>To</th>
            <th class="text-center">Reason</th>
            <th class="text-center">Status</th>
        </thead>
        <tbody>
            @forelse($leaves as $leave)
                <tr>
                    <td>{{ $leave->user->name }}</td>
                    <td>{{ $leave->leaveType->name }}</td>
                    <td>{{ $leave->from }}</td>
                    <td>{{ $leave->to }}</td>
                    <td class="text-center">
                        <a href="#" class="btn-view-leave-reason btn btn-info btn-xs"
                           data-url="{{ route('leaves.show', $leave->id) }}">
                            <i class="glyphicon glyphicon-book"></i> View reason
                        </a>
                    </td>
                    <td class="text-center">
                        @if($leave->status == 'pending')
                            <span class="label label-default">Pending</span>
                        @elseif($leave->status == 'approved')
                            <span class="label label-success">Approved</span>
                        @else
                            <span class="label" style="background-color: black">Rejected</span>
                        @endif
                    </td>
                </tr>
            @empty
                <tr class="bg-info text-center">
                    <td colspan="6">There's currently no leaves</td>
                </tr>
            @endforelse
        </tbody>
    </table>
@append

@section('js')
    <script>
        $(function () {
            $(".btn-view-leave-reason").click(function () {
                var url = $(this).data("url");

                $.get(url).success(function (result) {
                    var reason = result.data.reason;
                    alert(reason);
                });
            });
        });
    </script>
@append