app/Http/routes.php
<?php

Route::get('/', function () { return redirect('home'); });
Route::get('home', function () { return redirect()->route('leaves.index'); });

Route::controller('auth', 'Auth\AuthController');

Route::get('auth/logout', [
    'uses' => function () {
        Auth::logout();
        return redirect('auth/login');
    },
    'as' => 'auth.logout'
]);

Route::group(['middleware' => 'auth'], function () {

    Route::resource('users', 'UsersController');

    Route::resource('leave-types', 'LeaveTypesController');

    Route::put('leaves/{id}/approve', [
        'uses' => 'LeavesController@approve',
        'as'   => 'leaves.approve'
    ]);
    Route::put('leaves/{id}/reject', [
        'uses' => 'LeavesController@reject',
        'as'   => 'leaves.reject'
    ]);
    Route::resource('leaves', 'LeavesController');

});

app/Http/Controllers/LeaveTypesController.php
<?php

namespace App\Http\Controllers;

use App\Models\LeaveType;
use Illuminate\Http\Request;
use App\Http\Requests;
use Illuminate\Support\Facades\Auth;

class LeaveTypesController extends Controller
{
    public function callAction($method, $parameters)
    {
        // Only admin can access this controller
        $user = Auth::user();
        if ( ! $user->is_admin) {
            return app()->abort(403);
        }

        return parent::callAction($method, $parameters);
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $types = LeaveType::all();

        return view('leave_types.index', compact('types'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        $data = $request->only('name');
        $name = $request->get('name');

        // Check if this name already exists
        if (LeaveType::whereName($name)->count()) {
            return [
                'message' => 'This name already exists'
            ];
        }

        $newType = LeaveType::create($data);

        return [
            'success' => true,
            'data'    => $newType,
        ];
    }
}

resources/views/leave_types/index.blade.php
@extends('layout')

@section('content')
    <button class="btn-add-leave-type btn btn-default btn-sm"
            data-url="{{ route('leave-types.store') }}">
        <i class="glyphicon glyphicon-plus-sign"></i> Add Leave-type
    </button>
    <table id="tbl-leave-types" class="table table-condensed">
        <thead>
            <th>Name</th>
        </thead>
        <tbody>
            @forelse($types as $type)
                <tr>
                    <td>{{ $type->name }}</td>
                </tr>
            @empty
                <tr class="bg-info" id="tr-empty">
                    <td colspan="1">There's currently no leave-types</td>
                </tr>
            @endforelse
        </tbody>
    </table>
@append

@section('js')
    <script src="{{ asset('js/leave_types/index.js') }}"></script>
@append